/// PRADO country codes and document URLs
/// Source: https://www.consilium.europa.eu/prado/en/search-by-document-country.html

class PradoCountry {
  final String code;
  final String name;
  final String urlA;
  final String urlB;

  const PradoCountry({
    required this.code,
    required this.name,
    required this.urlA,
    required this.urlB,
  });
}

const String baseUrl = 'https://www.consilium.europa.eu/prado/en/prado-documents';

/// Generate document URLs for a country code
String getDocUrl(String code, String category) =>
    '$baseUrl/$code/$category/O/docs-per-type.html';

/// All PRADO countries with their document URLs
const List<PradoCountry> pradoCountries = [
  // EU Member States & PRADO Participating Countries
  PradoCountry(code: 'EUE', name: 'European Union', urlA: '$baseUrl/EUE/A/O/docs-per-type.html', urlB: '$baseUrl/EUE/B/O/docs-per-type.html'),
  PradoCountry(code: 'AUT', name: 'Austria', urlA: '$baseUrl/AUT/A/O/docs-per-type.html', urlB: '$baseUrl/AUT/B/O/docs-per-type.html'),
  PradoCountry(code: 'BEL', name: 'Belgium', urlA: '$baseUrl/BEL/A/O/docs-per-type.html', urlB: '$baseUrl/BEL/B/O/docs-per-type.html'),
  PradoCountry(code: 'BGR', name: 'Bulgaria', urlA: '$baseUrl/BGR/A/O/docs-per-type.html', urlB: '$baseUrl/BGR/B/O/docs-per-type.html'),
  PradoCountry(code: 'CYP', name: 'Cyprus', urlA: '$baseUrl/CYP/A/O/docs-per-type.html', urlB: '$baseUrl/CYP/B/O/docs-per-type.html'),
  PradoCountry(code: 'CZE', name: 'Czechia', urlA: '$baseUrl/CZE/A/O/docs-per-type.html', urlB: '$baseUrl/CZE/B/O/docs-per-type.html'),
  PradoCountry(code: 'DEU', name: 'Germany', urlA: '$baseUrl/DEU/A/O/docs-per-type.html', urlB: '$baseUrl/DEU/B/O/docs-per-type.html'),
  PradoCountry(code: 'DNK', name: 'Denmark', urlA: '$baseUrl/DNK/A/O/docs-per-type.html', urlB: '$baseUrl/DNK/B/O/docs-per-type.html'),
  PradoCountry(code: 'ESP', name: 'Spain', urlA: '$baseUrl/ESP/A/O/docs-per-type.html', urlB: '$baseUrl/ESP/B/O/docs-per-type.html'),
  PradoCountry(code: 'EST', name: 'Estonia', urlA: '$baseUrl/EST/A/O/docs-per-type.html', urlB: '$baseUrl/EST/B/O/docs-per-type.html'),
  PradoCountry(code: 'FIN', name: 'Finland', urlA: '$baseUrl/FIN/A/O/docs-per-type.html', urlB: '$baseUrl/FIN/B/O/docs-per-type.html'),
  PradoCountry(code: 'FRA', name: 'France', urlA: '$baseUrl/FRA/A/O/docs-per-type.html', urlB: '$baseUrl/FRA/B/O/docs-per-type.html'),
  PradoCountry(code: 'GRC', name: 'Greece', urlA: '$baseUrl/GRC/A/O/docs-per-type.html', urlB: '$baseUrl/GRC/B/O/docs-per-type.html'),
  PradoCountry(code: 'HRV', name: 'Croatia', urlA: '$baseUrl/HRV/A/O/docs-per-type.html', urlB: '$baseUrl/HRV/B/O/docs-per-type.html'),
  PradoCountry(code: 'HUN', name: 'Hungary', urlA: '$baseUrl/HUN/A/O/docs-per-type.html', urlB: '$baseUrl/HUN/B/O/docs-per-type.html'),
  PradoCountry(code: 'IRL', name: 'Ireland', urlA: '$baseUrl/IRL/A/O/docs-per-type.html', urlB: '$baseUrl/IRL/B/O/docs-per-type.html'),
  PradoCountry(code: 'ITA', name: 'Italy', urlA: '$baseUrl/ITA/A/O/docs-per-type.html', urlB: '$baseUrl/ITA/B/O/docs-per-type.html'),
  PradoCountry(code: 'LTU', name: 'Lithuania', urlA: '$baseUrl/LTU/A/O/docs-per-type.html', urlB: '$baseUrl/LTU/B/O/docs-per-type.html'),
  PradoCountry(code: 'LUX', name: 'Luxembourg', urlA: '$baseUrl/LUX/A/O/docs-per-type.html', urlB: '$baseUrl/LUX/B/O/docs-per-type.html'),
  PradoCountry(code: 'LVA', name: 'Latvia', urlA: '$baseUrl/LVA/A/O/docs-per-type.html', urlB: '$baseUrl/LVA/B/O/docs-per-type.html'),
  PradoCountry(code: 'MLT', name: 'Malta', urlA: '$baseUrl/MLT/A/O/docs-per-type.html', urlB: '$baseUrl/MLT/B/O/docs-per-type.html'),
  PradoCountry(code: 'NLD', name: 'Netherlands', urlA: '$baseUrl/NLD/A/O/docs-per-type.html', urlB: '$baseUrl/NLD/B/O/docs-per-type.html'),
  PradoCountry(code: 'POL', name: 'Poland', urlA: '$baseUrl/POL/A/O/docs-per-type.html', urlB: '$baseUrl/POL/B/O/docs-per-type.html'),
  PradoCountry(code: 'PRT', name: 'Portugal', urlA: '$baseUrl/PRT/A/O/docs-per-type.html', urlB: '$baseUrl/PRT/B/O/docs-per-type.html'),
  PradoCountry(code: 'ROU', name: 'Romania', urlA: '$baseUrl/ROU/A/O/docs-per-type.html', urlB: '$baseUrl/ROU/B/O/docs-per-type.html'),
  PradoCountry(code: 'SVK', name: 'Slovakia', urlA: '$baseUrl/SVK/A/O/docs-per-type.html', urlB: '$baseUrl/SVK/B/O/docs-per-type.html'),
  PradoCountry(code: 'SVN', name: 'Slovenia', urlA: '$baseUrl/SVN/A/O/docs-per-type.html', urlB: '$baseUrl/SVN/B/O/docs-per-type.html'),
  PradoCountry(code: 'SWE', name: 'Sweden', urlA: '$baseUrl/SWE/A/O/docs-per-type.html', urlB: '$baseUrl/SWE/B/O/docs-per-type.html'),
  PradoCountry(code: 'CHE', name: 'Switzerland', urlA: '$baseUrl/CHE/A/O/docs-per-type.html', urlB: '$baseUrl/CHE/B/O/docs-per-type.html'),
  PradoCountry(code: 'ISL', name: 'Iceland', urlA: '$baseUrl/ISL/A/O/docs-per-type.html', urlB: '$baseUrl/ISL/B/O/docs-per-type.html'),
  PradoCountry(code: 'NOR', name: 'Norway', urlA: '$baseUrl/NOR/A/O/docs-per-type.html', urlB: '$baseUrl/NOR/B/O/docs-per-type.html'),

  // Other Countries & Territories
  PradoCountry(code: 'LIE', name: 'Liechtenstein', urlA: '$baseUrl/LIE/A/O/docs-per-type.html', urlB: '$baseUrl/LIE/B/O/docs-per-type.html'),
  PradoCountry(code: 'AFG', name: 'Afghanistan', urlA: '$baseUrl/AFG/A/O/docs-per-type.html', urlB: '$baseUrl/AFG/B/O/docs-per-type.html'),
  PradoCountry(code: 'AGO', name: 'Angola', urlA: '$baseUrl/AGO/A/O/docs-per-type.html', urlB: '$baseUrl/AGO/B/O/docs-per-type.html'),
  PradoCountry(code: 'AIA', name: 'Anguilla', urlA: '$baseUrl/AIA/A/O/docs-per-type.html', urlB: '$baseUrl/AIA/B/O/docs-per-type.html'),
  PradoCountry(code: 'ALB', name: 'Albania', urlA: '$baseUrl/ALB/A/O/docs-per-type.html', urlB: '$baseUrl/ALB/B/O/docs-per-type.html'),
  PradoCountry(code: 'AND', name: 'Andorra', urlA: '$baseUrl/AND/A/O/docs-per-type.html', urlB: '$baseUrl/AND/B/O/docs-per-type.html'),
  PradoCountry(code: 'ARE', name: 'United Arab Emirates', urlA: '$baseUrl/ARE/A/O/docs-per-type.html', urlB: '$baseUrl/ARE/B/O/docs-per-type.html'),
  PradoCountry(code: 'ARG', name: 'Argentina', urlA: '$baseUrl/ARG/A/O/docs-per-type.html', urlB: '$baseUrl/ARG/B/O/docs-per-type.html'),
  PradoCountry(code: 'ARM', name: 'Armenia', urlA: '$baseUrl/ARM/A/O/docs-per-type.html', urlB: '$baseUrl/ARM/B/O/docs-per-type.html'),
  PradoCountry(code: 'AUS', name: 'Australia', urlA: '$baseUrl/AUS/A/O/docs-per-type.html', urlB: '$baseUrl/AUS/B/O/docs-per-type.html'),
  PradoCountry(code: 'AZE', name: 'Azerbaijan', urlA: '$baseUrl/AZE/A/O/docs-per-type.html', urlB: '$baseUrl/AZE/B/O/docs-per-type.html'),
  PradoCountry(code: 'BDI', name: 'Burundi', urlA: '$baseUrl/BDI/A/O/docs-per-type.html', urlB: '$baseUrl/BDI/B/O/docs-per-type.html'),
  PradoCountry(code: 'BEN', name: 'Benin', urlA: '$baseUrl/BEN/A/O/docs-per-type.html', urlB: '$baseUrl/BEN/B/O/docs-per-type.html'),
  PradoCountry(code: 'BFA', name: 'Burkina Faso', urlA: '$baseUrl/BFA/A/O/docs-per-type.html', urlB: '$baseUrl/BFA/B/O/docs-per-type.html'),
  PradoCountry(code: 'BGD', name: 'Bangladesh', urlA: '$baseUrl/BGD/A/O/docs-per-type.html', urlB: '$baseUrl/BGD/B/O/docs-per-type.html'),
  PradoCountry(code: 'BHR', name: 'Bahrain', urlA: '$baseUrl/BHR/A/O/docs-per-type.html', urlB: '$baseUrl/BHR/B/O/docs-per-type.html'),
  PradoCountry(code: 'BHS', name: 'Bahamas', urlA: '$baseUrl/BHS/A/O/docs-per-type.html', urlB: '$baseUrl/BHS/B/O/docs-per-type.html'),
  PradoCountry(code: 'BIH', name: 'Bosnia and Herzegovina', urlA: '$baseUrl/BIH/A/O/docs-per-type.html', urlB: '$baseUrl/BIH/B/O/docs-per-type.html'),
  PradoCountry(code: 'BLR', name: 'Belarus', urlA: '$baseUrl/BLR/A/O/docs-per-type.html', urlB: '$baseUrl/BLR/B/O/docs-per-type.html'),
  PradoCountry(code: 'BLZ', name: 'Belize', urlA: '$baseUrl/BLZ/A/O/docs-per-type.html', urlB: '$baseUrl/BLZ/B/O/docs-per-type.html'),
  PradoCountry(code: 'BMU', name: 'Bermuda', urlA: '$baseUrl/BMU/A/O/docs-per-type.html', urlB: '$baseUrl/BMU/B/O/docs-per-type.html'),
  PradoCountry(code: 'BRA', name: 'Brazil', urlA: '$baseUrl/BRA/A/O/docs-per-type.html', urlB: '$baseUrl/BRA/B/O/docs-per-type.html'),
  PradoCountry(code: 'BRN', name: 'Brunei Darussalam', urlA: '$baseUrl/BRN/A/O/docs-per-type.html', urlB: '$baseUrl/BRN/B/O/docs-per-type.html'),
  PradoCountry(code: 'BTN', name: 'Bhutan', urlA: '$baseUrl/BTN/A/O/docs-per-type.html', urlB: '$baseUrl/BTN/B/O/docs-per-type.html'),
  PradoCountry(code: 'BWA', name: 'Botswana', urlA: '$baseUrl/BWA/A/O/docs-per-type.html', urlB: '$baseUrl/BWA/B/O/docs-per-type.html'),
  PradoCountry(code: 'CAF', name: 'Central African Republic', urlA: '$baseUrl/CAF/A/O/docs-per-type.html', urlB: '$baseUrl/CAF/B/O/docs-per-type.html'),
  PradoCountry(code: 'CAN', name: 'Canada', urlA: '$baseUrl/CAN/A/O/docs-per-type.html', urlB: '$baseUrl/CAN/B/O/docs-per-type.html'),
  PradoCountry(code: 'CHL', name: 'Chile', urlA: '$baseUrl/CHL/A/O/docs-per-type.html', urlB: '$baseUrl/CHL/B/O/docs-per-type.html'),
  PradoCountry(code: 'CHN', name: 'China', urlA: '$baseUrl/CHN/A/O/docs-per-type.html', urlB: '$baseUrl/CHN/B/O/docs-per-type.html'),
  PradoCountry(code: 'CIV', name: 'Côte d\'Ivoire', urlA: '$baseUrl/CIV/A/O/docs-per-type.html', urlB: '$baseUrl/CIV/B/O/docs-per-type.html'),
  PradoCountry(code: 'CMR', name: 'Cameroon', urlA: '$baseUrl/CMR/A/O/docs-per-type.html', urlB: '$baseUrl/CMR/B/O/docs-per-type.html'),
  PradoCountry(code: 'COD', name: 'Democratic Republic of Congo', urlA: '$baseUrl/COD/A/O/docs-per-type.html', urlB: '$baseUrl/COD/B/O/docs-per-type.html'),
  PradoCountry(code: 'COG', name: 'Republic of the Congo', urlA: '$baseUrl/COG/A/O/docs-per-type.html', urlB: '$baseUrl/COG/B/O/docs-per-type.html'),
  PradoCountry(code: 'COL', name: 'Colombia', urlA: '$baseUrl/COL/A/O/docs-per-type.html', urlB: '$baseUrl/COL/B/O/docs-per-type.html'),
  PradoCountry(code: 'COM', name: 'Comoros', urlA: '$baseUrl/COM/A/O/docs-per-type.html', urlB: '$baseUrl/COM/B/O/docs-per-type.html'),
  PradoCountry(code: 'CPV', name: 'Cape Verde', urlA: '$baseUrl/CPV/A/O/docs-per-type.html', urlB: '$baseUrl/CPV/B/O/docs-per-type.html'),
  PradoCountry(code: 'CRI', name: 'Costa Rica', urlA: '$baseUrl/CRI/A/O/docs-per-type.html', urlB: '$baseUrl/CRI/B/O/docs-per-type.html'),
  PradoCountry(code: 'CUB', name: 'Cuba', urlA: '$baseUrl/CUB/A/O/docs-per-type.html', urlB: '$baseUrl/CUB/B/O/docs-per-type.html'),
  PradoCountry(code: 'DJI', name: 'Djibouti', urlA: '$baseUrl/DJI/A/O/docs-per-type.html', urlB: '$baseUrl/DJI/B/O/docs-per-type.html'),
  PradoCountry(code: 'DMA', name: 'Dominica', urlA: '$baseUrl/DMA/A/O/docs-per-type.html', urlB: '$baseUrl/DMA/B/O/docs-per-type.html'),
  PradoCountry(code: 'DOM', name: 'Dominican Republic', urlA: '$baseUrl/DOM/A/O/docs-per-type.html', urlB: '$baseUrl/DOM/B/O/docs-per-type.html'),
  PradoCountry(code: 'DZA', name: 'Algeria', urlA: '$baseUrl/DZA/A/O/docs-per-type.html', urlB: '$baseUrl/DZA/B/O/docs-per-type.html'),
  PradoCountry(code: 'ECU', name: 'Ecuador', urlA: '$baseUrl/ECU/A/O/docs-per-type.html', urlB: '$baseUrl/ECU/B/O/docs-per-type.html'),
  PradoCountry(code: 'EGY', name: 'Egypt', urlA: '$baseUrl/EGY/A/O/docs-per-type.html', urlB: '$baseUrl/EGY/B/O/docs-per-type.html'),
  PradoCountry(code: 'ERI', name: 'Eritrea', urlA: '$baseUrl/ERI/A/O/docs-per-type.html', urlB: '$baseUrl/ERI/B/O/docs-per-type.html'),
  PradoCountry(code: 'ETH', name: 'Ethiopia', urlA: '$baseUrl/ETH/A/O/docs-per-type.html', urlB: '$baseUrl/ETH/B/O/docs-per-type.html'),
  PradoCountry(code: 'FRO', name: 'Faroe Islands', urlA: '$baseUrl/FRO/A/O/docs-per-type.html', urlB: '$baseUrl/FRO/B/O/docs-per-type.html'),
  PradoCountry(code: 'GAB', name: 'Gabon', urlA: '$baseUrl/GAB/A/O/docs-per-type.html', urlB: '$baseUrl/GAB/B/O/docs-per-type.html'),
  PradoCountry(code: 'GBD', name: 'British Overseas Territories Citizen', urlA: '$baseUrl/GBD/A/O/docs-per-type.html', urlB: '$baseUrl/GBD/B/O/docs-per-type.html'),
  PradoCountry(code: 'GBR', name: 'United Kingdom', urlA: '$baseUrl/GBR/A/O/docs-per-type.html', urlB: '$baseUrl/GBR/B/O/docs-per-type.html'),
  PradoCountry(code: 'GEO', name: 'Georgia', urlA: '$baseUrl/GEO/A/O/docs-per-type.html', urlB: '$baseUrl/GEO/B/O/docs-per-type.html'),
  PradoCountry(code: 'GGY', name: 'Guernsey', urlA: '$baseUrl/GGY/A/O/docs-per-type.html', urlB: '$baseUrl/GGY/B/O/docs-per-type.html'),
  PradoCountry(code: 'GHA', name: 'Ghana', urlA: '$baseUrl/GHA/A/O/docs-per-type.html', urlB: '$baseUrl/GHA/B/O/docs-per-type.html'),
  PradoCountry(code: 'GIB', name: 'Gibraltar', urlA: '$baseUrl/GIB/A/O/docs-per-type.html', urlB: '$baseUrl/GIB/B/O/docs-per-type.html'),
  PradoCountry(code: 'GIN', name: 'Guinea', urlA: '$baseUrl/GIN/A/O/docs-per-type.html', urlB: '$baseUrl/GIN/B/O/docs-per-type.html'),
  PradoCountry(code: 'GMB', name: 'Gambia', urlA: '$baseUrl/GMB/A/O/docs-per-type.html', urlB: '$baseUrl/GMB/B/O/docs-per-type.html'),
  PradoCountry(code: 'GNB', name: 'Guinea-Bissau', urlA: '$baseUrl/GNB/A/O/docs-per-type.html', urlB: '$baseUrl/GNB/B/O/docs-per-type.html'),
  PradoCountry(code: 'GNQ', name: 'Equatorial Guinea', urlA: '$baseUrl/GNQ/A/O/docs-per-type.html', urlB: '$baseUrl/GNQ/B/O/docs-per-type.html'),
  PradoCountry(code: 'GRD', name: 'Grenada', urlA: '$baseUrl/GRD/A/O/docs-per-type.html', urlB: '$baseUrl/GRD/B/O/docs-per-type.html'),
  PradoCountry(code: 'GRL', name: 'Greenland', urlA: '$baseUrl/GRL/A/O/docs-per-type.html', urlB: '$baseUrl/GRL/B/O/docs-per-type.html'),
  PradoCountry(code: 'GUY', name: 'Guyana', urlA: '$baseUrl/GUY/A/O/docs-per-type.html', urlB: '$baseUrl/GUY/B/O/docs-per-type.html'),
  PradoCountry(code: 'HKG', name: 'Hong Kong', urlA: '$baseUrl/HKG/A/O/docs-per-type.html', urlB: '$baseUrl/HKG/B/O/docs-per-type.html'),
  PradoCountry(code: 'HND', name: 'Honduras', urlA: '$baseUrl/HND/A/O/docs-per-type.html', urlB: '$baseUrl/HND/B/O/docs-per-type.html'),
  PradoCountry(code: 'HTI', name: 'Haiti', urlA: '$baseUrl/HTI/A/O/docs-per-type.html', urlB: '$baseUrl/HTI/B/O/docs-per-type.html'),
  PradoCountry(code: 'IMN', name: 'Isle of Man', urlA: '$baseUrl/IMN/A/O/docs-per-type.html', urlB: '$baseUrl/IMN/B/O/docs-per-type.html'),
  PradoCountry(code: 'IND', name: 'India', urlA: '$baseUrl/IND/A/O/docs-per-type.html', urlB: '$baseUrl/IND/B/O/docs-per-type.html'),
  PradoCountry(code: 'IRN', name: 'Iran', urlA: '$baseUrl/IRN/A/O/docs-per-type.html', urlB: '$baseUrl/IRN/B/O/docs-per-type.html'),
  PradoCountry(code: 'IRQ', name: 'Iraq', urlA: '$baseUrl/IRQ/A/O/docs-per-type.html', urlB: '$baseUrl/IRQ/B/O/docs-per-type.html'),
  PradoCountry(code: 'ISR', name: 'Israel', urlA: '$baseUrl/ISR/A/O/docs-per-type.html', urlB: '$baseUrl/ISR/B/O/docs-per-type.html'),
  PradoCountry(code: 'JAM', name: 'Jamaica', urlA: '$baseUrl/JAM/A/O/docs-per-type.html', urlB: '$baseUrl/JAM/B/O/docs-per-type.html'),
  PradoCountry(code: 'JEY', name: 'Jersey', urlA: '$baseUrl/JEY/A/O/docs-per-type.html', urlB: '$baseUrl/JEY/B/O/docs-per-type.html'),
  PradoCountry(code: 'JOR', name: 'Jordan', urlA: '$baseUrl/JOR/A/O/docs-per-type.html', urlB: '$baseUrl/JOR/B/O/docs-per-type.html'),
  PradoCountry(code: 'JPN', name: 'Japan', urlA: '$baseUrl/JPN/A/O/docs-per-type.html', urlB: '$baseUrl/JPN/B/O/docs-per-type.html'),
  PradoCountry(code: 'KAZ', name: 'Kazakhstan', urlA: '$baseUrl/KAZ/A/O/docs-per-type.html', urlB: '$baseUrl/KAZ/B/O/docs-per-type.html'),
  PradoCountry(code: 'KEN', name: 'Kenya', urlA: '$baseUrl/KEN/A/O/docs-per-type.html', urlB: '$baseUrl/KEN/B/O/docs-per-type.html'),
  PradoCountry(code: 'KGZ', name: 'Kyrgyzstan', urlA: '$baseUrl/KGZ/A/O/docs-per-type.html', urlB: '$baseUrl/KGZ/B/O/docs-per-type.html'),
  PradoCountry(code: 'KHM', name: 'Cambodia', urlA: '$baseUrl/KHM/A/O/docs-per-type.html', urlB: '$baseUrl/KHM/B/O/docs-per-type.html'),
  PradoCountry(code: 'KNA', name: 'Saint Kitts and Nevis', urlA: '$baseUrl/KNA/A/O/docs-per-type.html', urlB: '$baseUrl/KNA/B/O/docs-per-type.html'),
  PradoCountry(code: 'KOR', name: 'Republic of Korea', urlA: '$baseUrl/KOR/A/O/docs-per-type.html', urlB: '$baseUrl/KOR/B/O/docs-per-type.html'),
  PradoCountry(code: 'KWT', name: 'Kuwait', urlA: '$baseUrl/KWT/A/O/docs-per-type.html', urlB: '$baseUrl/KWT/B/O/docs-per-type.html'),
  PradoCountry(code: 'LAO', name: 'Lao', urlA: '$baseUrl/LAO/A/O/docs-per-type.html', urlB: '$baseUrl/LAO/B/O/docs-per-type.html'),
  PradoCountry(code: 'LBN', name: 'Lebanon', urlA: '$baseUrl/LBN/A/O/docs-per-type.html', urlB: '$baseUrl/LBN/B/O/docs-per-type.html'),
  PradoCountry(code: 'LBR', name: 'Liberia', urlA: '$baseUrl/LBR/A/O/docs-per-type.html', urlB: '$baseUrl/LBR/B/O/docs-per-type.html'),
  PradoCountry(code: 'LBY', name: 'Libya', urlA: '$baseUrl/LBY/A/O/docs-per-type.html', urlB: '$baseUrl/LBY/B/O/docs-per-type.html'),
  PradoCountry(code: 'LKA', name: 'Sri Lanka', urlA: '$baseUrl/LKA/A/O/docs-per-type.html', urlB: '$baseUrl/LKA/B/O/docs-per-type.html'),
  PradoCountry(code: 'LSO', name: 'Lesotho', urlA: '$baseUrl/LSO/A/O/docs-per-type.html', urlB: '$baseUrl/LSO/B/O/docs-per-type.html'),
  PradoCountry(code: 'MAC', name: 'Macao', urlA: '$baseUrl/MAC/A/O/docs-per-type.html', urlB: '$baseUrl/MAC/B/O/docs-per-type.html'),
  PradoCountry(code: 'MAR', name: 'Morocco', urlA: '$baseUrl/MAR/A/O/docs-per-type.html', urlB: '$baseUrl/MAR/B/O/docs-per-type.html'),
  PradoCountry(code: 'MCO', name: 'Monaco', urlA: '$baseUrl/MCO/A/O/docs-per-type.html', urlB: '$baseUrl/MCO/B/O/docs-per-type.html'),
  PradoCountry(code: 'MDA', name: 'Republic of Moldova', urlA: '$baseUrl/MDA/A/O/docs-per-type.html', urlB: '$baseUrl/MDA/B/O/docs-per-type.html'),
  PradoCountry(code: 'MDG', name: 'Madagascar', urlA: '$baseUrl/MDG/A/O/docs-per-type.html', urlB: '$baseUrl/MDG/B/O/docs-per-type.html'),
  PradoCountry(code: 'MDV', name: 'Maldives', urlA: '$baseUrl/MDV/A/O/docs-per-type.html', urlB: '$baseUrl/MDV/B/O/docs-per-type.html'),
  PradoCountry(code: 'MEX', name: 'Mexico', urlA: '$baseUrl/MEX/A/O/docs-per-type.html', urlB: '$baseUrl/MEX/B/O/docs-per-type.html'),
  PradoCountry(code: 'MKD', name: 'North Macedonia', urlA: '$baseUrl/MKD/A/O/docs-per-type.html', urlB: '$baseUrl/MKD/B/O/docs-per-type.html'),
  PradoCountry(code: 'MLI', name: 'Mali', urlA: '$baseUrl/MLI/A/O/docs-per-type.html', urlB: '$baseUrl/MLI/B/O/docs-per-type.html'),
  PradoCountry(code: 'MNE', name: 'Montenegro', urlA: '$baseUrl/MNE/A/O/docs-per-type.html', urlB: '$baseUrl/MNE/B/O/docs-per-type.html'),
  PradoCountry(code: 'MNG', name: 'Mongolia', urlA: '$baseUrl/MNG/A/O/docs-per-type.html', urlB: '$baseUrl/MNG/B/O/docs-per-type.html'),
  PradoCountry(code: 'MOZ', name: 'Mozambique', urlA: '$baseUrl/MOZ/A/O/docs-per-type.html', urlB: '$baseUrl/MOZ/B/O/docs-per-type.html'),
  PradoCountry(code: 'MRT', name: 'Mauritania', urlA: '$baseUrl/MRT/A/O/docs-per-type.html', urlB: '$baseUrl/MRT/B/O/docs-per-type.html'),
  PradoCountry(code: 'MSR', name: 'Montserrat', urlA: '$baseUrl/MSR/A/O/docs-per-type.html', urlB: '$baseUrl/MSR/B/O/docs-per-type.html'),
  PradoCountry(code: 'MWI', name: 'Malawi', urlA: '$baseUrl/MWI/A/O/docs-per-type.html', urlB: '$baseUrl/MWI/B/O/docs-per-type.html'),
  PradoCountry(code: 'MYS', name: 'Malaysia', urlA: '$baseUrl/MYS/A/O/docs-per-type.html', urlB: '$baseUrl/MYS/B/O/docs-per-type.html'),
  PradoCountry(code: 'NAM', name: 'Namibia', urlA: '$baseUrl/NAM/A/O/docs-per-type.html', urlB: '$baseUrl/NAM/B/O/docs-per-type.html'),
  PradoCountry(code: 'NCL', name: 'New Caledonia', urlA: '$baseUrl/NCL/A/O/docs-per-type.html', urlB: '$baseUrl/NCL/B/O/docs-per-type.html'),
  PradoCountry(code: 'NGA', name: 'Nigeria', urlA: '$baseUrl/NGA/A/O/docs-per-type.html', urlB: '$baseUrl/NGA/B/O/docs-per-type.html'),
  PradoCountry(code: 'NIC', name: 'Nicaragua', urlA: '$baseUrl/NIC/A/O/docs-per-type.html', urlB: '$baseUrl/NIC/B/O/docs-per-type.html'),
  PradoCountry(code: 'NPL', name: 'Nepal', urlA: '$baseUrl/NPL/A/O/docs-per-type.html', urlB: '$baseUrl/NPL/B/O/docs-per-type.html'),
  PradoCountry(code: 'NZL', name: 'New Zealand', urlA: '$baseUrl/NZL/A/O/docs-per-type.html', urlB: '$baseUrl/NZL/B/O/docs-per-type.html'),
  PradoCountry(code: 'OMN', name: 'Oman', urlA: '$baseUrl/OMN/A/O/docs-per-type.html', urlB: '$baseUrl/OMN/B/O/docs-per-type.html'),
  PradoCountry(code: 'PAK', name: 'Pakistan', urlA: '$baseUrl/PAK/A/O/docs-per-type.html', urlB: '$baseUrl/PAK/B/O/docs-per-type.html'),
  PradoCountry(code: 'PAN', name: 'Panama', urlA: '$baseUrl/PAN/A/O/docs-per-type.html', urlB: '$baseUrl/PAN/B/O/docs-per-type.html'),
  PradoCountry(code: 'PER', name: 'Peru', urlA: '$baseUrl/PER/A/O/docs-per-type.html', urlB: '$baseUrl/PER/B/O/docs-per-type.html'),
  PradoCountry(code: 'PHL', name: 'Philippines', urlA: '$baseUrl/PHL/A/O/docs-per-type.html', urlB: '$baseUrl/PHL/B/O/docs-per-type.html'),
  PradoCountry(code: 'PLW', name: 'Palau', urlA: '$baseUrl/PLW/A/O/docs-per-type.html', urlB: '$baseUrl/PLW/B/O/docs-per-type.html'),
  PradoCountry(code: 'PRK', name: 'North Korea', urlA: '$baseUrl/PRK/A/O/docs-per-type.html', urlB: '$baseUrl/PRK/B/O/docs-per-type.html'),
  PradoCountry(code: 'PRY', name: 'Paraguay', urlA: '$baseUrl/PRY/A/O/docs-per-type.html', urlB: '$baseUrl/PRY/B/O/docs-per-type.html'),
  PradoCountry(code: 'PYF', name: 'French Polynesia', urlA: '$baseUrl/PYF/A/O/docs-per-type.html', urlB: '$baseUrl/PYF/B/O/docs-per-type.html'),
  PradoCountry(code: 'QAT', name: 'Qatar', urlA: '$baseUrl/QAT/A/O/docs-per-type.html', urlB: '$baseUrl/QAT/B/O/docs-per-type.html'),
  PradoCountry(code: 'RUS', name: 'Russian Federation', urlA: '$baseUrl/RUS/A/O/docs-per-type.html', urlB: '$baseUrl/RUS/B/O/docs-per-type.html'),
  PradoCountry(code: 'RWA', name: 'Rwanda', urlA: '$baseUrl/RWA/A/O/docs-per-type.html', urlB: '$baseUrl/RWA/B/O/docs-per-type.html'),
  PradoCountry(code: 'SAU', name: 'Saudi Arabia', urlA: '$baseUrl/SAU/A/O/docs-per-type.html', urlB: '$baseUrl/SAU/B/O/docs-per-type.html'),
  PradoCountry(code: 'SDN', name: 'Sudan', urlA: '$baseUrl/SDN/A/O/docs-per-type.html', urlB: '$baseUrl/SDN/B/O/docs-per-type.html'),
  PradoCountry(code: 'SEN', name: 'Senegal', urlA: '$baseUrl/SEN/A/O/docs-per-type.html', urlB: '$baseUrl/SEN/B/O/docs-per-type.html'),
  PradoCountry(code: 'SGP', name: 'Singapore', urlA: '$baseUrl/SGP/A/O/docs-per-type.html', urlB: '$baseUrl/SGP/B/O/docs-per-type.html'),
  PradoCountry(code: 'SHN', name: 'Saint Helena', urlA: '$baseUrl/SHN/A/O/docs-per-type.html', urlB: '$baseUrl/SHN/B/O/docs-per-type.html'),
  PradoCountry(code: 'SLE', name: 'Sierra Leone', urlA: '$baseUrl/SLE/A/O/docs-per-type.html', urlB: '$baseUrl/SLE/B/O/docs-per-type.html'),
  PradoCountry(code: 'SLV', name: 'El Salvador', urlA: '$baseUrl/SLV/A/O/docs-per-type.html', urlB: '$baseUrl/SLV/B/O/docs-per-type.html'),
  PradoCountry(code: 'SMR', name: 'San Marino', urlA: '$baseUrl/SMR/A/O/docs-per-type.html', urlB: '$baseUrl/SMR/B/O/docs-per-type.html'),
  PradoCountry(code: 'SOM', name: 'Somalia', urlA: '$baseUrl/SOM/A/O/docs-per-type.html', urlB: '$baseUrl/SOM/B/O/docs-per-type.html'),
  PradoCountry(code: 'SRB', name: 'Serbia', urlA: '$baseUrl/SRB/A/O/docs-per-type.html', urlB: '$baseUrl/SRB/B/O/docs-per-type.html'),
  PradoCountry(code: 'SSD', name: 'South Sudan', urlA: '$baseUrl/SSD/A/O/docs-per-type.html', urlB: '$baseUrl/SSD/B/O/docs-per-type.html'),
  PradoCountry(code: 'STP', name: 'Sao Tome and Principe', urlA: '$baseUrl/STP/A/O/docs-per-type.html', urlB: '$baseUrl/STP/B/O/docs-per-type.html'),
  PradoCountry(code: 'SUR', name: 'Suriname', urlA: '$baseUrl/SUR/A/O/docs-per-type.html', urlB: '$baseUrl/SUR/B/O/docs-per-type.html'),
  PradoCountry(code: 'SYC', name: 'Seychelles', urlA: '$baseUrl/SYC/A/O/docs-per-type.html', urlB: '$baseUrl/SYC/B/O/docs-per-type.html'),
  PradoCountry(code: 'SYR', name: 'Syrian Arab Republic', urlA: '$baseUrl/SYR/A/O/docs-per-type.html', urlB: '$baseUrl/SYR/B/O/docs-per-type.html'),
  PradoCountry(code: 'TCA', name: 'Turks and Caicos Islands', urlA: '$baseUrl/TCA/A/O/docs-per-type.html', urlB: '$baseUrl/TCA/B/O/docs-per-type.html'),
  PradoCountry(code: 'TCD', name: 'Chad', urlA: '$baseUrl/TCD/A/O/docs-per-type.html', urlB: '$baseUrl/TCD/B/O/docs-per-type.html'),
  PradoCountry(code: 'TGO', name: 'Togo', urlA: '$baseUrl/TGO/A/O/docs-per-type.html', urlB: '$baseUrl/TGO/B/O/docs-per-type.html'),
  PradoCountry(code: 'THA', name: 'Thailand', urlA: '$baseUrl/THA/A/O/docs-per-type.html', urlB: '$baseUrl/THA/B/O/docs-per-type.html'),
  PradoCountry(code: 'TKM', name: 'Turkmenistan', urlA: '$baseUrl/TKM/A/O/docs-per-type.html', urlB: '$baseUrl/TKM/B/O/docs-per-type.html'),
  PradoCountry(code: 'TLS', name: 'Timor-Leste', urlA: '$baseUrl/TLS/A/O/docs-per-type.html', urlB: '$baseUrl/TLS/B/O/docs-per-type.html'),
  PradoCountry(code: 'TUN', name: 'Tunisia', urlA: '$baseUrl/TUN/A/O/docs-per-type.html', urlB: '$baseUrl/TUN/B/O/docs-per-type.html'),
  PradoCountry(code: 'TUR', name: 'Türkiye', urlA: '$baseUrl/TUR/A/O/docs-per-type.html', urlB: '$baseUrl/TUR/B/O/docs-per-type.html'),
  PradoCountry(code: 'TUV', name: 'Tuvalu', urlA: '$baseUrl/TUV/A/O/docs-per-type.html', urlB: '$baseUrl/TUV/B/O/docs-per-type.html'),
  PradoCountry(code: 'TWN', name: 'Taiwan', urlA: '$baseUrl/TWN/A/O/docs-per-type.html', urlB: '$baseUrl/TWN/B/O/docs-per-type.html'),
  PradoCountry(code: 'TZA', name: 'United Republic of Tanzania', urlA: '$baseUrl/TZA/A/O/docs-per-type.html', urlB: '$baseUrl/TZA/B/O/docs-per-type.html'),
  PradoCountry(code: 'UGA', name: 'Uganda', urlA: '$baseUrl/UGA/A/O/docs-per-type.html', urlB: '$baseUrl/UGA/B/O/docs-per-type.html'),
  PradoCountry(code: 'UKR', name: 'Ukraine', urlA: '$baseUrl/UKR/A/O/docs-per-type.html', urlB: '$baseUrl/UKR/B/O/docs-per-type.html'),
  PradoCountry(code: 'URY', name: 'Uruguay', urlA: '$baseUrl/URY/A/O/docs-per-type.html', urlB: '$baseUrl/URY/B/O/docs-per-type.html'),
  PradoCountry(code: 'USA', name: 'United States', urlA: '$baseUrl/USA/A/O/docs-per-type.html', urlB: '$baseUrl/USA/B/O/docs-per-type.html'),
  PradoCountry(code: 'UZB', name: 'Uzbekistan', urlA: '$baseUrl/UZB/A/O/docs-per-type.html', urlB: '$baseUrl/UZB/B/O/docs-per-type.html'),
  PradoCountry(code: 'VAT', name: 'Vatican City State', urlA: '$baseUrl/VAT/A/O/docs-per-type.html', urlB: '$baseUrl/VAT/B/O/docs-per-type.html'),
  PradoCountry(code: 'VEN', name: 'Venezuela', urlA: '$baseUrl/VEN/A/O/docs-per-type.html', urlB: '$baseUrl/VEN/B/O/docs-per-type.html'),
  PradoCountry(code: 'VGB', name: 'British Virgin Islands', urlA: '$baseUrl/VGB/A/O/docs-per-type.html', urlB: '$baseUrl/VGB/B/O/docs-per-type.html'),
  PradoCountry(code: 'VNM', name: 'Viet Nam', urlA: '$baseUrl/VNM/A/O/docs-per-type.html', urlB: '$baseUrl/VNM/B/O/docs-per-type.html'),
  PradoCountry(code: 'YEM', name: 'Yemen', urlA: '$baseUrl/YEM/A/O/docs-per-type.html', urlB: '$baseUrl/YEM/B/O/docs-per-type.html'),
  PradoCountry(code: 'ZAF', name: 'South Africa', urlA: '$baseUrl/ZAF/A/O/docs-per-type.html', urlB: '$baseUrl/ZAF/B/O/docs-per-type.html'),
  PradoCountry(code: 'ZMB', name: 'Zambia', urlA: '$baseUrl/ZMB/A/O/docs-per-type.html', urlB: '$baseUrl/ZMB/B/O/docs-per-type.html'),
  PradoCountry(code: 'ZWE', name: 'Zimbabwe', urlA: '$baseUrl/ZWE/A/O/docs-per-type.html', urlB: '$baseUrl/ZWE/B/O/docs-per-type.html'),

  // International Organizations & Special Entities
  PradoCountry(code: 'INT', name: 'International Organisations', urlA: '$baseUrl/INT/A/O/docs-per-type.html', urlB: '$baseUrl/INT/B/O/docs-per-type.html'),
  PradoCountry(code: 'OPT', name: 'Occupied Palestinian Territory', urlA: '$baseUrl/OPT/A/O/docs-per-type.html', urlB: '$baseUrl/OPT/B/O/docs-per-type.html'),
  PradoCountry(code: 'UAP', name: 'African Union Staff', urlA: '$baseUrl/UAP/A/O/docs-per-type.html', urlB: '$baseUrl/UAP/B/O/docs-per-type.html'),
  PradoCountry(code: 'UNO', name: 'United Nations Official', urlA: '$baseUrl/UNO/A/O/docs-per-type.html', urlB: '$baseUrl/UNO/B/O/docs-per-type.html'),
  PradoCountry(code: 'XEC', name: 'ECOWAS', urlA: '$baseUrl/XEC/A/O/docs-per-type.html', urlB: '$baseUrl/XEC/B/O/docs-per-type.html'),
  PradoCountry(code: 'XKX', name: 'Kosovo', urlA: '$baseUrl/XKX/A/O/docs-per-type.html', urlB: '$baseUrl/XKX/B/O/docs-per-type.html'),
  PradoCountry(code: 'XOM', name: 'Sovereign Military Order of Malta', urlA: '$baseUrl/XOM/A/O/docs-per-type.html', urlB: '$baseUrl/XOM/B/O/docs-per-type.html'),
  PradoCountry(code: 'XPO', name: 'INTERPOL', urlA: '$baseUrl/XPO/A/O/docs-per-type.html', urlB: '$baseUrl/XPO/B/O/docs-per-type.html'),
];
