sonar.projectKey=privacybydesign_vcmrtd
sonar.organization=privacybydesign

sonar.sources=lib
sonar.tests=test
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,example/**,docs/**

sonar.dart.lcov.reportPaths=coverage/lcov.info
